# Generated by Django 5.1.3 on 2024-11-14 08:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_alter_bill_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
