# Generated by Django 5.1.3 on 2024-11-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_alter_bill_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='product_uses',
            field=models.TextField(default=''),
        ),
    ]
