# Generated by Django 5.1.3 on 2024-11-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_product_description_product_product_uses'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='objects_used',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.IntegerField(default=0.0005454545454545454),
            preserve_default=False,
        ),
    ]
