# Generated by Django 5.1.3 on 2024-11-18 15:21

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0012_checkout_order_delete_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='full_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Thanh toán khi nhận hàng'), ('MOMO', 'Thanh toán qua MOMO'), ('VISA', 'Thanh toán qua VISA')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkout',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+84999999999'. Up to 12 digits allowed.", regex='^(\\+84|0)\\d{8,12}$')]),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='status',
            field=models.CharField(choices=[('Pending', 'Xác thực đơn hàng'), ('Delivering', 'Đang vận chuyển'), ('Delivered', 'Đã vận chuyển')], default='Pending', max_length=100),
        ),
    ]
